<?php

namespace Bankroll\Includes\ACF;

class Helpers
{
    public static function tabs(string $postType, array $fields = []): array
    {
        $type = ucfirst($postType);

        if (!empty($postType) && !empty($fields)) {
            return array(
                'key' => "group_{$postType}_6547d0a971d4d",
                'title' => 'Globals',
                'fields' => array(
                    array(
                        'key' => "field_{$postType}_6547d0a9f5bba",
                        'label' => "{$type} Data",
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => "field_{$postType}_6547d112f5bbb",
                        'label' => 'Blocks',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    $fields['blocks']
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'post_type',
                            'operator' => '==',
                            'value' => $postType,
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            );
        }
    }

    public static function blocks(string $postType): array
    {
        return array(
            'key' => 'field_' . $postType . '_63e9667077abb',
            'label' => 'Content Blocks',
            'name' => 'blocks',
            'aria-label' => '',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                'layout_' . $postType . '_63eac6a9bacc8' => array(
                    'key' => 'layout_' . $postType . '_63eac6a9bacc8',
                    'name' => 'block_board',
                    'label' => 'Board',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_' . $postType . '_63eea9090d141',
                            'label' => 'Data',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_' . $postType . '_63eeb98701365',
                            'label' => 'Block Data',
                            'name' => 'block_data',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_' . $postType . '_63eac79dbaccb',
                                    'label' => 'Type',
                                    'name' => 'block_board_post_type',
                                    'aria-label' => '',
                                    'type' => 'select',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        'slot' => 'Slot',
                                        'casino' => 'Casino',
                                    ),
                                    'default_value' => false,
                                    'return_format' => 'value',
                                    'multiple' => 0,
                                    'allow_null' => 0,
                                    'ui' => 0,
                                    'ajax' => 0,
                                    'placeholder' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_643272e40fef8',
                                    'label' => 'Card Style',
                                    'name' => 'block_board_card_style',
                                    'aria-label' => '',
                                    'type' => 'button_group',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'choices' => array(
                                        1 => '1',
                                        2 => '2',
                                        3 => '3',
                                    ),
                                    'default_value' => '',
                                    'return_format' => 'value',
                                    'allow_null' => 0,
                                    'layout' => 'horizontal',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_63f1eafbac92b',
                                    'label' => 'Show All Posts',
                                    'name' => 'block_board_show_all',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '33.3',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                    'ui' => 1,
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_63eeafd3ed04f',
                                    'label' => 'Slots',
                                    'name' => 'block_board_slot',
                                    'aria-label' => '',
                                    'type' => 'relationship',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_' . $postType . '_63eac79dbaccb',
                                                'operator' => '==',
                                                'value' => 'slot',
                                            ),
                                            array(
                                                'field' => 'field_' . $postType . '_63f1eafbac92b',
                                                'operator' => '!=',
                                                'value' => '1',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'slot',
                                    ),
                                    'taxonomy' => '',
                                    'filters' => array(
                                        0 => 'search',
                                        1 => 'taxonomy',
                                    ),
                                    'return_format' => 'object',
                                    'min' => '',
                                    'max' => '',
                                    'elements' => '',
                                    'bidirectional_target' => array(),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_' . $postType . '_63eea9620d142',
                            'label' => 'Block Settings',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_' . $postType . '_63eeaafb4a63f',
                            'label' => 'Block Settings',
                            'name' => 'block_settings',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_' . $postType . '_63eea9a10d143',
                                    'label' => 'Title',
                                    'name' => 'block_title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9933fa31',
                                    'label' => 'Subtitle',
                                    'name' => 'block_subtitle',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_63eea9c70d144',
                                    'label' => 'Content Before',
                                    'name' => 'block_content_before',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_63f158bd5cf63',
                                    'label' => 'Content After',
                                    'name' => 'block_content_after',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_' . $postType . '_63f7e58712457' => array(
                    'key' => 'layout_' . $postType . '_63f7e58712457',
                    'name' => 'block_content',
                    'label' => 'Content',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_' . $postType . '_63f7e74b1245c',
                            'label' => 'Data',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_' . $postType . '_63f7e837c85bd',
                            'label' => 'Block Data',
                            'name' => 'block_data',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_' . $postType . '_63f7e7951245e',
                                    'label' => 'Editor',
                                    'name' => 'block_content_editor',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_' . $postType . '_63f7e7621245d',
                            'label' => 'Block Settings',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_' . $postType . '_653ed9cc97e8f',
                            'label' => 'Block Settings',
                            'name' => 'block_settings',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_' . $postType . '_653ed9cc97e90',
                                    'label' => 'Title',
                                    'name' => 'block_title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9cc97e91',
                                    'label' => 'Subtitle',
                                    'name' => 'block_subtitle',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9cc97e92',
                                    'label' => 'Content Before',
                                    'name' => 'block_content_before',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9cc97e93',
                                    'label' => 'Content After',
                                    'name' => 'block_content_after',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                'layout_' . $postType . '_653ed756af2c4' => array(
                    'key' => 'layout_' . $postType . '_653ed756af2c4',
                    'name' => 'block_toplist',
                    'label' => 'Toplist',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_' . $postType . '_653ed756af2c5',
                            'label' => 'Data',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_' . $postType . '_653ed756af2c6',
                            'label' => 'Block Data',
                            'name' => 'block_data',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_' . $postType . '_653ed756af2c7',
                                    'label' => 'Editor',
                                    'name' => 'block_toplist_items',
                                    'aria-label' => '',
                                    'type' => 'relationship',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'toplist',
                                    ),
                                    'post_status' => '',
                                    'taxonomy' => '',
                                    'filters' => array(
                                        0 => 'search',
                                    ),
                                    'return_format' => 'id',
                                    'min' => '',
                                    'max' => '',
                                    'elements' => '',
                                    'bidirectional' => 0,
                                    'bidirectional_target' => array(),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_' . $postType . '_653ed756af2c8',
                            'label' => 'Block Settings',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'top',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_' . $postType . '_653ed9e297e94',
                            'label' => 'Block Settings',
                            'name' => 'block_settings',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_' . $postType . '_653ed9e297e95',
                                    'label' => 'Title',
                                    'name' => 'block_title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9e297e96',
                                    'label' => 'Subtitle',
                                    'name' => 'block_subtitle',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9e297e97',
                                    'label' => 'Content Before',
                                    'name' => 'block_content_before',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                                array(
                                    'key' => 'field_' . $postType . '_653ed9e297e98',
                                    'label' => 'Content After',
                                    'name' => 'block_content_after',
                                    'aria-label' => '',
                                    'type' => 'wysiwyg',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'tabs' => 'all',
                                    'toolbar' => 'full',
                                    'media_upload' => 1,
                                    'delay' => 0,
                                ),
                            ),
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
            ),
            'min' => '',
            'max' => '',
            'button_label' => 'New Block',
        );
    }
}
